### ISSUE TITLE
query error on cpu panel

### ISSUE THREAD

**Issue by yldrmdgn** [egmc/egmc-grafana-dashboards#1]
Thanks for your beautiful dashboard. but I face with a problem. I have been using grafana 8 version. What should change on it?
sum(rate(namedprocess_namegroup_cpu_seconds_total{instance=~"sw01:9256"}[$__rate_interval] ))  by (groupname)
![2021-09-23_17h05_56](https://user-images.githubusercontent.com/46830964/134467783-666c2293-e6e2-46e2-915c-0a1d46911e43.png)

**Comment by egmc** [comment]
Hi @yldrmdgn 

Thank you for using this dashboard.

Unfortunately, I don't have exact answer for that. At least, in my environment, Grafana 8(8.1.4) and Treemap Plugin(0.9.0) are working and show cpu map graph properly.  I could only guess some possible reasons just like bellow..

- query itself looks good, please make sure the query for namedprocess_namegroup_cpu_seconds_total rertuns correct result
- cpu map using same query of cpu graph, just get latest value with a instant query.If you can see the cpu graph, it might be a problem caused by timerange(for instance, when timerange set as "today", there's no result and show the error like that)

for example,I'll share my settings and sample result.

query:
sum﻿(﻿rate﻿(﻿namedprocess_namegroup_cpu_seconds_total﻿{﻿instance﻿=~﻿"myhostname:9256"﻿}﻿[$__rate_interval﻿] ﻿)﻿)﻿  ﻿by﻿ ﻿(﻿groupname﻿) 

result:
```
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"groupname":"apache2"},"value":[1632474675,"0"]},{"metric":{"groupname":"exporters"},"value":[1632474675,"0.0031111111111385976"]},{"metric":{"groupname":"monitor processes"},"value":[1632474675,"0.00622222222215593"]},{"metric":{"groupname":"root processes"},"value":[1632474675,"0.001555555555569299"]},{"metric":{"groupname":"sshd processes"},"value":[1632474675,"0"]},{"metric":{"groupname":"_apt processes"},"value":[1632474675,"0"]},{"metric":{"groupname":"daemon processes"},"value":[1632474675,"0"]},{"metric":{"groupname":"egmc processes"},"value":[1632474675,"0"]},{"metric":{"groupname":"man processes"},"value":[1632474675,"0"]},{"metric":{"groupname":"messagebus processes"},"value":[1632474675,"0"]},{"metric":{"groupname":"sh"},"value":[1632474675,"0"]},{"metric":{"groupname":"grafana processes"},"value":[1632474675,"0.0004444444444516193"]},{"metric":{"groupname":"mysqld"},"value":[1632474675,"0.0004444444444440402"]},{"metric":{"groupname":"nobody processes"},"value":[1632474675,"0"]},{"metric":{"groupname":"perl"},"value":[1632474675,"0"]},{"metric":{"groupname":"syslog processes"},"value":[1632474675,"0"]},{"metric":{"groupname":"www-data processes"},"value":[1632474675,"0"]}]}}
```

setting for process-exporeter:

```
command=/usr/local/bin/process-exporter -threads=false -config.path /usr/local/etc/process_exporter.yaml
```

```
 cat /usr/local/etc/process_exporter.yaml
process_names:
  - comm:
    - php-fpm7.2
    - mysqld
    - memcached
    - apache2
  - name: "exporters"
    cmdline:
    - '/usr/local/bin/.+[_-]exporter'
  - name: "{{.Username}} processes"
    cmdline:
    - '.+'
```

**Comment by 976311200** [comment]
HI @egmc 
I want to know the detailed process CPU usage but failed.
failed query:
(sum (rate(namedprocess_namegroup_cpu_seconds_total{groupname="$processes"}[$interval]) )by(groupname))/(sum(rate(namedprocess_namegroup_cpu_seconds_total[$interval])))*100
sucess query:
(sum (rate(namedprocess_namegroup_cpu_seconds_total{groupname="$processes"}[$interval]) )by(groupname))
sucess  query:
(sum(rate(namedprocess_namegroup_cpu_seconds_total[$interval])))

How can i make it work to show the detailed cpu usage in Grafana?

**Comment by egmc** [comment]
Hi @976311200 ,

Your question seems to be not related this dashboard.
But I guess, failed query may have label mismatch since the query on left side has  a groupname label.
So if you add `ignoring(groupname)` like this, that cloud work.

```
(sum (rate(namedprocess_namegroup_cpu_seconds_total{groupname="$processes"}[$interval]) )by(groupname))/ ignoring(groupname)
 (sum(rate(namedprocess_namegroup_cpu_seconds_total[$interval])))*100
```

I tested with apache2 groupname as an example.

![image](https://github.com/egmc/egmc-grafana-dashboards/assets/1496561/27af35a9-b3e2-40da-b90c-271419fc909b)
